name: Build iOS Simulator

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    env:
      PYTHONUTF8: "1"
      FLET_CLI_NO_RICH_OUTPUT: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Show Flet version
        run: |
          uv run flet --version

      - name: Build iOS Simulator
        run: |
          uv run flet build ios-simulator --yes --verbose

      - name: Upload iOS Simulator build
        uses: actions/upload-artifact@v7
        with:
          name: ios-simulator-build
          path: build/ios-simulator
          if-no-files-found: error
